[tools]
bat = "latest"
bat-extras = "latest"
btop = "latest"
bun = "latest"
lazygit = "latest"
node = "latest"
opencode = "latest"
pnpm = "latest"
rust = "nightly"
usage = "latest"
uv = "latest"
yazi = "latest"
yq = "latest"
zoxide = "latest"
lua = "latest"
gh = "latest"
fzf = "latest"

